// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config({
  path: process.env.APP_ENV === "production" || process.env.NODE_ENV === "production" ? ".env.production" : ".env.local",
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node -r ts-node/register/transpile-only prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
